app:
    resource: "@AppBundle/Controller/"
    type:     annotation

show :
    path: /show/{id} 
    defaults: { _controller: AppBundle:Default:show } 

form :
   path: /form
   defaults: { _controller:AppBundle:Default:form }